//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceWebApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CompanyCard
    {
        public string CardNumber { get; set; }
        public System.DateTime Validity { get; set; }
        public string CardTypeNo { get; set; }
        public decimal Balance { get; set; }
        public string UserName { get; set; }

        public Card Card { get; set; }
        public Consumer Consumer { get; set; }
    }
}
